In [ ]:
  import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
abs=10.22557889652365895123578951222222398745
abs=long
print(abs)

 numpy:                      array operations,
 pandas:                     DAta manipulation and analysis,
 matplotlib and seaborn:     Graphical analysis,
 sklearn MAchine leanring:   algorithms and techniques,
 statsmodels:                Statistical analysis,
 scipy:                      statiscial analysis,

In [ ]:
   ```python
   import numpy as np
   import pandas as pd
   import matplotlib.pyplot as plt
   ```
   The `as np`, `as pd`, and `as plt` are aliases that make it easier to refer to the libraries in your code.



SyntaxError: invalid syntax (<ipython-input-7-28e028d1659a>, line 1)

In [ ]:
import numpy as pd

In [ ]:
j=[4,45,5,6,7,5]
j

[4, 45, 5, 6, 7, 5]

In [ ]:
d=np.array(j)
d


array([ 4, 45,  5,  6,  7,  5])

In [ ]:
type(d)

numpy.ndarray

In [ ]:
tuple(j)

(4, 45, 5, 6, 7, 5)

In [ ]:
d

array([ 4, 45,  5,  6,  7,  5])

In [ ]:
d.shape

(6,)

In [ ]:
d.ndim

1

In [ ]:
d.size

6

In [ ]:
h=d.reshape(2,3)
h

array([[ 4, 45,  5],
       [ 6,  7,  5]])

In [ ]:
import numpy as np
a=[[9,3,4,5,6,7,],[8,4,2,2,7,8,],[3,4,6,7,8,8,7],[3,3,5,6,78,44,2,2]]
print(a)

[[9, 3, 4, 5, 6, 7], [8, 4, 2, 2, 7, 8], [3, 4, 6, 7, 8, 8, 7], [3, 3, 5, 6, 78, 44, 2, 2]]


In [ ]:
type(a)

list

In [ ]:
np.array(a)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [ ]:
h.size

6

In [ ]:
h.shape

(2, 3)

In [ ]:
h.ndim

2